name: CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        -main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: Chechout code
      uses: actions/checkout